INSERT INTO
  products (
    product_id,
    name,
    description,
    category,
    gender,
    price,
    size,
    quantity,
    brand
  )
VALUES
  (
    1,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    129.99,
    7,
    20,
    'Nike'
  ),
  (
    2,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    129.99,
    8,
    20,
    'Nike'
  ),
  (
    3,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    129.99,
    9,
    20,
    'Nike'
  ),
  (
    4,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    139.99,
    10,
    20,
    'Nike'
  ),
  (
    5,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    139.99,
    11,
    20,
    'Nike'
  ),
  (
    6,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    6,
    30,
    'Adidas'
  ),
  (
    7,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    7,
    30,
    'Adidas'
  ),
  (
    8,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    9,
    30,
    'Adidas'
  ),
  (
    9,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    239.98,
    10,
    30,
    'Adidas'
  ),
  (
    10,
    'Classic Leather',
    'Reebok Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    89.99,
    5,
    30,
    'Reebok'
  ),
  (
    11,
    'Classic Leather',
    'Reebok Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    89.99,
    6,
    30,
    'Reebok'
  ),
  (
    12,
    'Classic Leather',
    'Reebok Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    89.99,
    7,
    30,
    'Reebok'
  ),
  (
    13,
    'Classic Leather',
    'Reebok Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    99.99,
    8,
    30,
    'Reebok'
  ),
  (
    14,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    7,
    30,
    'Adidas'
  ),
  (
    15,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    8,
    30,
    'Adidas'
  ),
  (
    16,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    9,
    30,
    'Adidas'
  ),
  (
    17,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    6,
    120,
    'Converse'
  ),
  (
    18,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    7,
    120,
    'Converse'
  ),
  (
    19,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    10,
    120,
    'Converse'
  ),
  (
    20,
    'Gel-Kayano 27',
    'ASICS Gel-Kayano 27 running shoes with superior stability.',
    'Running',
    'man',
    160.50,
    9,
    40,
    'ASICS'
  ),
  (
    21,
    'Gel-Kayano 27',
    'ASICS Gel-Kayano 27 running shoes with superior stability.',
    'Running',
    'man',
    160.50,
    10,
    40,
    'ASICS'
  ),
  (
    22,
    'Gel-Kayano 27',
    'ASICS Gel-Kayano 27 running shoes with superior stability.',
    'Running',
    'man',
    160.50,
    11,
    40,
    'ASICS'
  ),
  (
    23,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    8,
    25,
    'Adidas'
  ),
  (
    24,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    9,
    25,
    'Adidas'
  ),
  (
    25,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    10,
    25,
    'Adidas'
  ),
  (
    26,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'woman',
    250.00,
    6,
    15,
    'Nike'
  ),
  (
    27,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'woman',
    250.00,
    7,
    15,
    'Nike'
  ),
  (
    28,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'woman',
    250.00,
    8,
    15,
    'Nike'
  );