INSERT INTO
  products (
    product_id,
    name,
    description,
    category,
    gender,
    price,
    size,
    quantity,
    brand,
    image_url
  )
VALUES
  (
    1,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'men',
    129.99,
    7,
    20,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-90.png'
  ),
  (
    2,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'men',
    129.99,
    8,
    20,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-90.png'
  ),
  (
    3,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'men',
    129.99,
    9,
    20,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-90.png'
  ),
  (
    4,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'men',
    139.99,
    10,
    20,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-90.png'
  ),
  (
    5,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'men',
    139.99,
    11,
    20,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-90.png'
  ),
  (
    6,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    6,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/yeezy-boost-350.png'
  ),
  (
    7,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    7,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/yeezy-boost-350.png'
  ),
  (
    8,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    9,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/yeezy-boost-350.png'
  ),
  (
    9,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    239.98,
    10,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/yeezy-boost-350.png'
  ),
  (
    10,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'women',
    89.99,
    5,
    30,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/carina-leather.png'
  ),
  (
    11,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'women',
    89.99,
    6,
    30,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/carina-leather.png'
  ),
  (
    12,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'women',
    89.99,
    7,
    30,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/carina-leather.png'
  ),
  (
    13,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'women',
    99.99,
    8,
    30,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/carina-leather.png'
  ),
  (
    14,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    7,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/stan-smith.png'
  ),
  (
    15,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    8,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/stan-smith.png'
  ),
  (
    16,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    9,
    30,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/stan-smith.png'
  ),
  (
    17,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    6,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/chuck-taylor.png'
  ),
  (
    18,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    7,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/chuck-taylor.png'
  ),
  (
    19,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    10,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/chuck-taylor.png'
  ),
  (
    20,
    'Deviate Nitro 3',
    'Deviate Nitro 3 running shoes with superior stability.',
    'Running',
    'men',
    160.50,
    9,
    40,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/deviate-nitro-3.png'
  ),
  (
    21,
    'Deviate Nitro 3',
    'Deviate Nitro 3 running shoes with superior stability.',
    'Running',
    'men',
    160.50,
    10,
    40,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/deviate-nitro-3.png'
  ),
  (
    22,
    'Deviate Nitro 3',
    'Deviate Nitro 3 running shoes with superior stability.',
    'Running',
    'men',
    160.50,
    11,
    40,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/deviate-nitro-3.png'
  ),
  (
    23,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    8,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/ultraboost-21.png'
  ),
  (
    24,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    9,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/ultraboost-21.png'
  ),
  (
    25,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    10,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/ultraboost-21.png'
  ),
  (
    26,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'women',
    250.00,
    6,
    15,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/vaporx.png'
  ),
  (
    27,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'women',
    250.00,
    7,
    15,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/vaporx.png'
  ),
  (
    28,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'women',
    250.00,
    8,
    15,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/vaporx.png'
  ),
  (
    29,
    'Jordan 1',
    'Timeless sneakers from the only GOAT',
    'Sneakers',
    'unisex',
    280.00,
    8,
    25,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-1.png'
  ),
  (
    30,
    'Jordan 1',
    'Timeless sneakers from the only GOAT',
    'Sneakers',
    'unisex',
    280.00,
    9,
    25,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-1.png'
  ),
  (
    31,
    'Jordan 1',
    'Timeless sneakers from the only GOAT',
    'Sneakers',
    'unisex',
    280.00,
    10,
    25,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-1.png'
  ),
  (
    32,
    'CDG Chuck',
    'Crafted by the exceptional Japanese Designer',
    'Casual',
    'women',
    190.00,
    6,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/comme-des-garcons-chuck.png'
  ),
  (
    33,
    'CDG Chuck',
    'Crafted by the exceptional Japanese Designer',
    'Casual',
    'women',
    190.00,
    7,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/comme-des-garcons-chuck.png'
  ),
  (
    34,
    'CDG Chuck',
    'Crafted by the exceptional Japanese Designer',
    'Casual',
    'women',
    190.00,
    10,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/comme-des-garcons-chuck.png'
  ),
  (
    35,
    'Granola Chuck',
    'Made for daily use',
    'Casual',
    'men',
    90.00,
    6,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/granola-chuck.png'
  ),
  (
    36,
    'Granola Chuck',
    'Made for daily use',
    'Casual',
    'men',
    90.00,
    7,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/granola-chuck.png'
  ),
  (
    37,
    'Granola Chuck',
    'Made for daily use',
    'Casual',
    'men',
    90.00,
    10,
    120,
    'Converse',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/granola-chuck.png'
  ),
  (
    38,
    'Air Max 97',
    'Made for daily use',
    'Sneakers',
    'men',
    150.00,
    6,
    120,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-97.png'
  ),
  (
    39,
    'Air Max 97',
    'Made for daily use',
    'Sneakers',
    'men',
    150.00,
    7,
    120,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-97.png'
  ),
  (
    40,
    'Air Max 97',
    'Made for daily use',
    'Sneakers',
    'men',
    150.00,
    10,
    120,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/air-max-97.png'
  ),
  (
    41,
    'TRC Blaze HC',
    'Made for daily use',
    'Running',
    'unisex',
    120.00,
    6,
    120,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/trc-blaze-hc.png'
  ),
  (
    42,
    'TRC Blaze HC',
    'Made for daily use',
    'Running',
    'unisex',
    120.00,
    7,
    120,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/trc-blaze-hc.png'
  ),
  (
    43,
    'TRC Blaze HC',
    'Made for daily use',
    'Running',
    'unisex',
    120.00,
    10,
    120,
    'Puma',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/trc-blaze-hc.png'
  ),
  (
    44,
    'Jordan 4',
    'Timeless sneakers from the only GOAT',
    'Sneakers',
    'unisex',
    270.00,
    8,
    25,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-4.png'
  ),
  (
    45,
    'Jordan 4',
    'Timeless sneakers from the only GOAT',
    'Sneakers',
    'unisex',
    270.00,
    9,
    25,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-4.png'
  ),
  (
    46,
    'Jordan 4',
    'Timeless sneakers from the only GOAT',
    'Sneakers',
    'unisex',
    270.00,
    10,
    25,
    'Nike',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-4.png'
  ),
  (
    47,
    'NMD Pharrell Williams',
    'Show up your creative spark',
    'Sneakers',
    'unisex',
    330.00,
    8,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/jordan-4.png'
  ),
  (
    48,
    'NMD Pharrell Williams',
    'Show up your creative spark',
    'Sneakers',
    'unisex',
    330.00,
    9,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/nmd-pharrell-williams.png'
  ),
  (
    49,
    'NMD Pharrell Williams',
    'Show up your creative spark',
    'Sneakers',
    'unisex',
    330.00,
    10,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/nmd-pharrell-williams.png'
  ),
  (
    50,
    'Gazelle Indoor',
    'Show up your creative spark',
    'Sneakers',
    'women',
    70.00,
    8,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/gazelle-indoor.png'
  ),
  (
    51,
    'Gazelle Indoor',
    'Show up your creative spark',
    'Sneakers',
    'women',
    70.00,
    9,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/gazelle-indoor.png'
  ),
  (
    52,
    'Gazelle Indoor',
    'Show up your creative spark',
    'Sneakers',
    'women',
    70.00,
    10,
    25,
    'Adidas',
    'https://cdn.jsdelivr.net/gh/cyprus09/ie4717-project@components/assets/product/gazelle-indoor.png'
  );