INSERT INTO
  products (
    product_id,
    name,
    description,
    category,
    gender,
    price,
    size,
    quantity,
    brand,
    image_url
  )
VALUES
-- Air Max 90
  (
    1,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    129.99,
    7,
    20,
    'Nike',
    'https://drive.google.com/thumbnail?id=1xuCUh_i_z-wuVhUZc_ogvRBfmCMX2yEW&sz=w1000'
  ),
  (
    2,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    129.99,
    8,
    20,
    'Nike',
    'https://drive.google.com/thumbnail?id=1xuCUh_i_z-wuVhUZc_ogvRBfmCMX2yEW&sz=w1000'
  ),
  (
    3,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    129.99,
    9,
    20,
    'Nike',
    'https://drive.google.com/thumbnail?id=1xuCUh_i_z-wuVhUZc_ogvRBfmCMX2yEW&sz=w1000'
  ),
  (
    4,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    139.99,
    10,
    20,
    'Nike',
    'https://drive.google.com/thumbnail?id=1xuCUh_i_z-wuVhUZc_ogvRBfmCMX2yEW&sz=w1000'
  ),
  (
    5,
    'Air Max 90',
    'Nike Air Max 90 sneakers with comfortable cushioning.',
    'Sneakers',
    'man',
    139.99,
    11,
    20,
    'Nike',
    'https://drive.google.com/thumbnail?id=1xuCUh_i_z-wuVhUZc_ogvRBfmCMX2yEW&sz=w1000'
  ),

-- Yeezy Boost 350

  (
    6,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    6,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1tLCrQydNqb1HRrgGsHU6dkVtr1E4HqXD&sz=w1000'
  ),
  (
    7,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    7,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1tLCrQydNqb1HRrgGsHU6dkVtr1E4HqXD&sz=w1000'
  ),
  (
    8,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    229.98,
    9,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1tLCrQydNqb1HRrgGsHU6dkVtr1E4HqXD&sz=w1000'
  ),
  (
    9,
    'Yeezy Boost 350',
    'Adidas Yeezy Boost 350 with primeknit upper.',
    'Sneakers',
    'unisex',
    239.98,
    10,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1tLCrQydNqb1HRrgGsHU6dkVtr1E4HqXD&sz=w1000'
  ),
  (
    10,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    89.99,
    5,
    30,
    'Puma',
    'https://drive.google.com/thumbnail?id=1jLUbJbTmrc8gySMwhMFr8ZiqR3I-O-m9&sz=w1000'
  ),
  (
    11,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    89.99,
    6,
    30,
    'Puma',
    'https://drive.google.com/thumbnail?id=1jLUbJbTmrc8gySMwhMFr8ZiqR3I-O-m9&sz=w1000'
  ),
  (
    12,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    89.99,
    7,
    30,
    'Puma',
    'https://drive.google.com/thumbnail?id=1jLUbJbTmrc8gySMwhMFr8ZiqR3I-O-m9&sz=w1000'
  ),
  (
    13,
    'Carina Leather',
    'Puma Classic Leather shoes with a retro design.',
    'Casual',
    'woman',
    99.99,
    8,
    30,
    'Puma',
    'https://drive.google.com/thumbnail?id=1jLUbJbTmrc8gySMwhMFr8ZiqR3I-O-m9&sz=w1000'
  ),
  (
    14,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    7,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1Y8Xo-T-ryMpsC6Y6_cWqYLSUlSXNtqK3&sz=w1000'
  ),
  (
    15,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    8,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1Y8Xo-T-ryMpsC6Y6_cWqYLSUlSXNtqK3&sz=w1000'
  ),
  (
    16,
    'Stan Smith',
    'Adidas Stan Smith iconic tennis shoes.',
    'Casual',
    'unisex',
    75.99,
    9,
    30,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1Y8Xo-T-ryMpsC6Y6_cWqYLSUlSXNtqK3&sz=w1000'
  ),
  (
    17,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    6,
    120,
    'Converse',
    'https://drive.google.com/thumbnail?id=1uhI5ZOb46y7OMUzD6vR2SQ1w3qCCXzjA&sz=w1000'
  ),
  (
    18,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    7,
    120,
    'Converse',
    'https://drive.google.com/thumbnail?id=1uhI5ZOb46y7OMUzD6vR2SQ1w3qCCXzjA&sz=w1000'
  ),
  (
    19,
    'Chuck Taylor All Star',
    'Converse Chuck Taylor All Star high-top sneakers.',
    'Casual',
    'unisex',
    60.00,
    10,
    120,
    'Converse',
    'https://drive.google.com/thumbnail?id=1uhI5ZOb46y7OMUzD6vR2SQ1w3qCCXzjA&sz=w1000'
  ),
  (
    20,
    'Deviate Nitro 3',
    'Deviate Nitro 3 running shoes with superior stability.',
    'Running',
    'man',
    160.50,
    9,
    40,
    'Puma',
    'https://drive.google.com/thumbnail?id=1iczx520wMJ-SV83JdexRd9mzWm7eq342&sz=w1000'
  ),
  (
    21,
    'Deviate Nitro 3',
    'Deviate Nitro 3 running shoes with superior stability.',
    'Running',
    'man',
    160.50,
    10,
    40,
    'Puma',
    'https://drive.google.com/thumbnail?id=1iczx520wMJ-SV83JdexRd9mzWm7eq342&sz=w1000'
  ),
  (
    22,
    'Deviate Nitro 3',
    'Deviate Nitro 3 running shoes with superior stability.',
    'Running',
    'man',
    160.50,
    11,
    40,
    'Puma',
    'https://drive.google.com/thumbnail?id=1iczx520wMJ-SV83JdexRd9mzWm7eq342&sz=w1000'
  ),
  (
    23,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    8,
    25,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1yAcTjg0-RcIRkEgvdptA_3_BpXhtTmy3&sz=w1000'
  ),
  (
    24,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    9,
    25,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1yAcTjg0-RcIRkEgvdptA_3_BpXhtTmy3&sz=w1000'
  ),
  (
    25,
    'UltraBoost 21',
    'Adidas UltraBoost 21 with responsive cushioning.',
    'Running',
    'unisex',
    180.00,
    10,
    25,
    'Adidas',
    'https://drive.google.com/thumbnail?id=1yAcTjg0-RcIRkEgvdptA_3_BpXhtTmy3&sz=w1000'
  ),
  (
    26,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'woman',
    250.00,
    6,
    15,
    'Nike',
    'https://drive.google.com/thumbnail?id=1urzMm9PlMazPNHegCRjUwuseQD0VmK3j&sz=w1000'
  ),
  (
    27,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'woman',
    250.00,
    7,
    15,
    'Nike',
    'https://drive.google.com/thumbnail?id=1urzMm9PlMazPNHegCRjUwuseQD0VmK3j&sz=w1000'
  ),
  (
    28,
    'ZoomX Vaporfly',
    'Nike ZoomX Vaporfly Next% 2 for marathon running.',
    'Running',
    'woman',
    250.00,
    8,
    15,
    'Nike',
    'https://drive.google.com/thumbnail?id=1urzMm9PlMazPNHegCRjUwuseQD0VmK3j&sz=w1000'
  );